"""empty message

Revision ID: 0f429454e42d
Revises: e0ffed43c278
Create Date: 2019-04-11 11:12:54.832341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f429454e42d'
down_revision = 'e0ffed43c278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendess', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attendess')
    # ### end Alembic commands ###
